FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY consumer.js ./

EXPOSE 8081
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:9092
ENV KAFKA_CONSUMER_GROUP=ecommerce-consumer-group
CMD ["node", "consumer.js"]
