FROM apache/spark:3.5.1

USER root
WORKDIR /app
COPY . .

# Create the ivy2 cache directory
RUN mkdir -p /tmp/.ivy2/cache && chmod -R 777 /tmp/.ivy2

# Give user 185 ownership of the /app directory so it can write checkpoints
RUN chown -R 185:185 /app

USER 185